app = 'lms-switchfully'
primary_region = 'ams'

[build]

[[mounts]]
source = 'tmp'
destination = '/tmp'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1